# mkdocs.yml

# --- Project Information ---
site_name: OmniRAG Cloud-Native DevOps Showcase
site_url: https://omnirag.anpham.me/docs/
site_description: A comprehensive documentation for OmniRAG chatbot, showcasing cloud-native DevOps, Kubernetes, CI/CD, IaC, and GitOps.
site_author: An Pham
repo_name: phamduchongan93/omnirag-devops-showcase
repo_url: https://github.com/phamduchongan93/omnirag-devops-showcase

# --- Theme Configuration ---
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  icon:
    logo: material/rocket-launch
  favicon: assets/favicon.ico

# --- Navigation Structure ---
nav:
  - Home: index.md
  - Architecture: architecture.md
  - DevOps Workflow: devops_workflow.md
  - Setup Guide: setup_guide.md
  - Demo Script: demo_script.md
  - Formal Requirements: /home/anpham/Project/showcase/omnirag-devops-showcase/docs/requirements/OmniRAG_requirement.pdf
# Link to your compiled LaTeX PDF
  - About:
    - Author: about/author.md # Optional: Create this file for more info about yourself
    - Contact: about/contact.md # Optional: Create this file

# --- Plugins ---
plugins:
  - search
  - pdf-export:
      verbose: false
      show_secondary_info: false
      output_path: pdf/document.pdf
      cover_title: "OmniRAG Documentation"
      cover_subtitle: "Cloud-Native DevOps Showcase"
      cover_author: "An Pham"
  # --- Markdown Extensions ---
# These enable additional Markdown features like admonitions, footnotes, etc.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition # For the :material-robot-happy: type blocks
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list # Needed for classes like `{.lg .middle}` on icons, and grid cards
  - md_in_html # Allows Markdown inside HTML tags
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true # For tabbed content
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# --- Extra Files (for assets like favicon, images, etc.) ---
# MkDocs copies these files/directories into the 'site' output directory.
extra_css:
  - stylesheets/extra.css # Optional: For custom CSS
extra_javascript:
  - javascripts/extra.js # Optional: For custom JavaScript

# Add your generated diagrams and other images
extra_templates: [] # No extra templates usually needed here for images
extra_css: []
extra_javascript: []
# Make sure your diagrams are in docs/img/ and will be picked up by MkDocs
# E.g., if diagrams are generated in docs/img/, just linking to them in markdown works.
# If you have other assets like favicon, put them in docs/assets/
# For example, if you create docs/assets/favicon.ico
# extra_css:
#  - assets/stylesheets/extra.css
# extra_javascript:
#  - assets/javascripts/extra.js
